//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: wxTestDesigns.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_wxTestDesigns_H__
#define __WDR_wxTestDesigns_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "wxTestDesigns_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

// Declare menubar functions

const int ID_FileMenu = 10000;
const int ID_TEST = 10001;
wxMenuBar *MyMenuBarFunc();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
