//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: vtkViewer.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma implementation "vtkViewer_wdr.h"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "vtkViewer_wdr.h"


// Euro sign hack of the year
#if wxUSE_UNICODE
    #define __WDR_EURO__ wxT("\u20ac")
#else
    #if defined(__WXMAC__)
        #define __WDR_EURO__ wxT("\xdb")
    #elif defined(__WXMSW__)
        #define __WDR_EURO__ wxT("\x80")
    #else
        #define __WDR_EURO__ wxT("\xa4")
    #endif
#endif

// Custom source
#include "wxVTKRenderWindowInteractor.h"
#include "VtkCanvas.h"

// Implement window functions

wxSizer *CreateVtkCanvas( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxVTKRenderWindowInteractor *item1 = new wxVTKRenderWindowInteractor( parent, ID_VTK_INTERACTOR, wxDefaultPosition, wxSize(640,480), 0 );
    item0->Add( item1, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *CreateVtkViewer( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    VtkCanvas *item1 = new VtkCanvas( parent, ID_CANVAS, wxDefaultPosition, wxSize(640,480), 0 );
    item0->Add( item1, 1, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

// Implement menubar functions

wxMenuBar *VtkViewerMenu()
{
    wxMenuBar *item0 = new wxMenuBar( wxMB_DOCKABLE );
    
    wxMenu* item1 = new wxMenu( wxMENU_TEAROFF );
    item1->Append( ID_FILE_OPEN, wxT("&Open\tCtrl-O"), wxT("Open a file") );
    item1->Append( ID_FILE_EXIT, wxT("&Exit\tCtrl-X"), wxT("") );
    item0->Append( item1, wxT("File") );
    
    return item0;
}

// Implement toolbar functions

// Implement bitmap functions


// End of generated file
