// -*- C++ -*- generated by wxGlade 0.4.1 on Thu Oct 19 12:07:54 2006

#include "AboutDialog.h"


AboutDialog::AboutDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: AboutDialog::AboutDialog
    txtLabel = new wxStaticText(this, -1, wxT("ImageTracker"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE);
    btnOK = new wxButton(this, wxID_OK, wxT("&OK"));

    set_properties();
    do_layout();
    // end wxGlade
}


void AboutDialog::set_properties()
{
    // begin wxGlade: AboutDialog::set_properties
    SetTitle(wxT("About ImageTracker"));
    SetSize(wxSize(330, 100));
    btnOK->SetDefault();
    // end wxGlade
}


void AboutDialog::do_layout()
{
    // begin wxGlade: AboutDialog::do_layout
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    sizer_8->Add(txtLabel, 1, wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 0);
    sizer_8->Add(btnOK, 0, wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 0);
    SetAutoLayout(true);
    SetSizer(sizer_8);
    Layout();
    // end wxGlade
}

