// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Feb  9 12:45:04 2007

#include <wx/wx.h>
#include <wx/image.h>

#include "ApplyTransformsPipeline.h"
#include "DataSource.h"
#include "ImageTrackerController.h"
        
#ifndef APPLYTRANSFORMDIALOG_H
#define APPLYTRANSFORMDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade


class ApplyTransformDialog: public wxDialog {
public:
    // begin wxGlade: ApplyTransformDialog::ids
    // end wxGlade
    enum IDs
    {
        BTN_BROWSE_TRANSFORM = 3060,
        BTN_BROWSE_DIRECTORY
    };
    
    ApplyTransformDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: ApplyTransformDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ApplyTransformDialog::attributes
    wxStaticBox* sizer_31_staticbox;
    wxStaticBox* sizer_30_staticbox;
    wxStaticText* label_25;
    wxTextCtrl* textTransform;
    wxButton* btnBrowse;
    wxStaticText* label_26;
    wxTextCtrl* textDirectory;
    wxButton* btnBrowseDirectory;
    wxStaticText* label_27;
    wxTextCtrl* textPrefix;
    wxCheckBox* checkOpenOutput;
    wxButton* btnRun;
    wxButton* btnHide;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnBrowseTransform(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnBrowseDirectory(wxCommandEvent &event); // wxGlade: <event_handler>
    
public:
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    void SetInput(DataSource::Pointer input);
    void SetController(ImageTrackerController::Pointer controller);
    
protected:
    
private:
    DataSource::Pointer input;
    ImageTrackerController::Pointer controller;
    ApplyTransformsPipeline::Pointer pipeline;
    
}; // wxGlade: end class


#endif // APPLYTRANSFORMDIALOG_H
