// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Jul 31 15:10:16 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CLGOPTICALFLOWDIALOG_H
#define CLGOPTICALFLOWDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilePatternPanel.h"
#include "wxIntSlider.h"
#include "wxDoubleSlider.h"

// end wxGlade

#include "ImageFileSet.h"
#include "MultiResolutionOpticalFlowPipeline.h"
#include "ScalarImageVisualization.h"

class CLGOpticalFlowDialog: public wxDialog {
public:
    // begin wxGlade: CLGOpticalFlowDialog::ids
    enum {
        SLIDE_DERIVATIVE_SCALE = wxID_HIGHEST + 1072,
        SLIDE_INTEGRATION_SCALE = wxID_HIGHEST + 1073
    };
    // end wxGlade

    CLGOpticalFlowDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    
    void SetInput(ImageFileSet* input);

private:
    // begin wxGlade: CLGOpticalFlowDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    
    bool preview;
    ImageFileSet* input;
    MultiResolutionOpticalFlowPipeline::Pointer pipeline;
    ScalarImageVisualization::Pointer visual;

protected:
    // begin wxGlade: CLGOpticalFlowDialog::attributes
    wxStaticBox* sizer_26_staticbox;
    wxStaticBox* sizer_27_staticbox;
    wxStaticText* label_15;
    wxDoubleSlider* slideDerivativeScale;
    wxStaticText* label_16;
    wxDoubleSlider* slideIntegrationScale;
    wxStaticText* label_11;
    wxIntSlider* slideLevels;
    wxStaticText* label_20;
    wxIntSlider* slideIterations;
    wxStaticText* label_19;
    wxDoubleSlider* slideRegularization;
    FilePatternPanel* panelFilePattern;
    wxCheckBox* checkOpenOutput;
    wxButton* buttonRun;
    wxButton* buttonHide;
    // end wxGlade

    DECLARE_EVENT_TABLE();
    
    void ViewPreview(bool show);
    void UpdatePreview();

public:
    virtual void OnDerivativeScale(wxCommandEvent &event);
    virtual void OnIntegrationScale(wxCommandEvent &event);
    virtual void OnRun(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnHide(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // CLGOPTICALFLOWDIALOG_H
