// -*- C++ -*- generated by wxGlade 0.4.1 on Thu Oct 19 12:42:02 2006

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DATASOURCEDIALOG_H
#define DATASOURCEDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

#include "DataSource.h"
#include "FilePatternDialog.h"

class DataSourceDialog: public wxDialog {
public:
    // begin wxGlade: DataSourceDialog::ids
    // end wxGlade

    DataSourceDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    enum IDs
    {
        BTN_ADD_EXAMPLE       = 3000,
        BTN_ADD_PATTERN,
        BTN_ADD_SELECTION,
        BTN_REMOVE
    };
    
private:
    // begin wxGlade: DataSourceDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DataSourceDialog::attributes
    wxStaticBox* sizer_11_staticbox;
    wxStaticText* label_2;
    wxTextCtrl* txtName;
    wxRadioBox* rbxPixelType;
    wxListBox* lbxFiles;
    wxButton* btnAddExample;
    wxButton* btnAddPattern;
    wxButton* btnAddSelection;
    wxButton* btnRemove;
    wxButton* btnOk;
    wxButton* btnCancel;
    // end wxGlade

    FilePatternDialog* dlgFilePattern;
    
    DECLARE_EVENT_TABLE();

public:
    void OnRemoveFiles(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnAddExample(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnAddPattern(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnAddSelection(wxCommandEvent &event); // wxGlade: <event_handler>
    
public:
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    void SetDataSource(DataSource::Pointer dataSource);
    DataSource::Pointer GetDataSource();
    void ClearDataSource();
    void SetNewSource(bool isNew) { this->newSource = isNew; }
    bool IsNewSource() { return this->newSource; }
    
private:
    DataSource::Pointer dataSource;
    bool newSource;
}; // wxGlade: end class


#endif // DATASOURCEDIALOG_H
