// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Aug 20 16:39:59 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIFFERENCEOFGAUSSIANSPANEL_H
#define DIFFERENCEOFGAUSSIANSPANEL_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilterControlPanel.h"
#include "wxDoubleSlider.h"

// end wxGlade

#include "itkRecursiveGaussianImageFilter.h"
#include "itkSubtractImageFilter.h"

class DifferenceOfGaussiansPanel: public FilterControlPanel {
public:
    // begin wxGlade: DifferenceOfGaussiansPanel::ids
    enum {
        SLIDE_SIGMA_1 = wxID_HIGHEST + 1166,
        SLIDE_SIGMA_2 = wxID_HIGHEST + 1167
    };
    // end wxGlade

    DifferenceOfGaussiansPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);
    
    typedef FilterControlPanel::ImageType ImageType;
    typedef itk::RecursiveGaussianImageFilter< ImageType, ImageType > GaussianType;
    typedef itk::SubtractImageFilter< ImageType, ImageType, ImageType > SubtractType;
    
    virtual void SetInput(const ImageType* image);
    virtual ImageType* GetOutput();

private:
    // begin wxGlade: DifferenceOfGaussiansPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    GaussianType::Pointer gaussians[4];
    SubtractType::Pointer subtract;
    
protected:
    // begin wxGlade: DifferenceOfGaussiansPanel::attributes
    wxStaticBox* sizer_13_staticbox;
    wxStaticText* label_41;
    wxDoubleSlider* slideSigma1;
    wxStaticText* label_54;
    wxDoubleSlider* slideSigma2;
    // end wxGlade
    
    DECLARE_EVENT_TABLE();

public:
    virtual void OnSigma(wxCommandEvent &event);
}; // wxGlade: end class


#endif // DIFFERENCEOFGAUSSIANSPANEL_H
