// -*- C++ -*- generated by wxGlade 0.4.1 on Tue Aug 21 12:13:10 2007

#include "EmptyVisualizationControl.h"


EmptyVisualizationControl::EmptyVisualizationControl(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: EmptyVisualizationControl::EmptyVisualizationControl
    label_35 = new wxStaticText(this, -1, wxT("This visualization has no configurable settings."));

    set_properties();
    do_layout();
    // end wxGlade
}


void EmptyVisualizationControl::set_properties()
{
    // begin wxGlade: EmptyVisualizationControl::set_properties
    // end wxGlade
}


void EmptyVisualizationControl::do_layout()
{
    // begin wxGlade: EmptyVisualizationControl::do_layout
    wxBoxSizer* sizer_39 = new wxBoxSizer(wxHORIZONTAL);
    sizer_39->Add(label_35, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
    SetAutoLayout(true);
    SetSizer(sizer_39);
    sizer_39->Fit(this);
    sizer_39->SetSizeHints(this);
    // end wxGlade
}

