// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Oct 12 13:28:42 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FILEPATTERNDIALOG_H
#define FILEPATTERNDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

#include "FilePattern.h"
#include "FilePatternPanel.h"

class FilePatternDialog: public wxDialog {
public:
    // begin wxGlade: FilePatternDialog::ids
    // end wxGlade

    FilePatternDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME);

    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    
    void SetFilePattern(const FilePattern& pattern);
    FilePattern GetFilePattern();
    
private:
    // begin wxGlade: FilePatternDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: FilePatternDialog::attributes
    FilePatternPanel* panelFilePattern;
    wxButton* buttonOK;
    wxButton* buttonCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnOK(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // FILEPATTERNDIALOG_H
