// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Oct 12 11:02:51 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FILEPATTERNPANEL_H
#define FILEPATTERNPANEL_H

#include "FilePattern.h"

// begin wxGlade: ::dependencies
// end wxGlade


class FilePatternPanel: public wxPanel {
public:
    // begin wxGlade: FilePatternPanel::ids
    enum {
        TEXT_DIRECTORY = wxID_HIGHEST + 1109,
        BUTTON_BROWSE = wxID_HIGHEST + 1111,
        TEXT_PREFIX = wxID_HIGHEST + 1113,
        TEXT_NUMBER_FORMAT = wxID_HIGHEST + 1115,
        TEXT_EXTENSION = wxID_HIGHEST + 1117,
        TEXT_RANGE_START = wxID_HIGHEST + 1119,
        TEXT_RANGE_END = wxID_HIGHEST + 1121
    };
    // end wxGlade
    
    FilePatternPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    
    void SetFilePattern(const FilePattern& pattern);
    FilePattern GetFilePattern();
    
    void SetExtensionEnabled(bool enable);
    bool GetExtensionEnabled();
    void SetRangeEnabled(bool enable);
    bool GetRangeEnabled();
    
private:
    // begin wxGlade: FilePatternPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    FilePattern pattern;
    
protected:
    // begin wxGlade: FilePatternPanel::attributes
    wxStaticText* label_62;
    wxTextCtrl* textDirectory;
    wxButton* buttonBrowse;
    wxStaticText* label_57_copy;
    wxTextCtrl* textPrefix;
    wxStaticText* label_58_copy;
    wxTextCtrl* textNumberFormat;
    wxStaticText* label_7;
    wxStaticText* label_59_copy;
    wxTextCtrl* textExtension;
    wxStaticText* label_63_copy;
    wxStaticText* label_64_copy;
    wxTextCtrl* textRangeStart;
    wxStaticText* label_65_copy;
    wxTextCtrl* textRangeEnd;
    wxStaticText* label_60_copy;
    wxStaticText* labelExample;
    // end wxGlade

    DECLARE_EVENT_TABLE();
    
    void UpdateExample();

public:
    void OnDirectory(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnPrefix(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnFormat(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnExtension(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnRangeStart(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnRangeEnd(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // FILEPATTERNPANEL_H
