// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Aug  4 14:55:52 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GAUSSIANFILTERPANEL_H
#define GAUSSIANFILTERPANEL_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilterControlPanel.h"
#include "wxDoubleSlider.h"

// end wxGlade

#include "itkRecursiveGaussianImageFilter.h"

class GaussianFilterPanel: public FilterControlPanel {
public:
    // begin wxGlade: GaussianFilterPanel::ids
    enum {
        SLIDE_SIGMA_X = wxID_HIGHEST + 1122,
        COMBO_ORDER_X = wxID_HIGHEST + 1123,
        SLIDE_SIGMA_Y = wxID_HIGHEST + 1125,
        COMBO_ORDER_Y = wxID_HIGHEST + 1126
    };
    // end wxGlade

    GaussianFilterPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

    typedef FilterControlPanel::ImageType ImageType;
    typedef itk::RecursiveGaussianImageFilter< ImageType, ImageType > GaussianType;
    
    virtual void SetInput(const ImageType* input);
    virtual ImageType* GetOutput();
    
private:
    // begin wxGlade: GaussianFilterPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    
    GaussianType::Pointer gaussians[2];

protected:
    // begin wxGlade: GaussianFilterPanel::attributes
    wxStaticBox* sizer_5_staticbox;
    wxStaticText* label_2;
    wxDoubleSlider* slideSigmaX;
    wxComboBox* comboOrderX;
    wxStaticText* label_17;
    wxDoubleSlider* slideSigmaY;
    wxComboBox* comboOrderY;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnSigma(wxCommandEvent &event);
    virtual void OnOrder(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // GAUSSIANFILTERPANEL_H
