// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Aug 14 10:29:00 2008

#include "GradientMagnitudePanel.h"

// begin wxGlade: ::extracode

// end wxGlade


GradientMagnitudePanel::GradientMagnitudePanel(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    FilterControlPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: GradientMagnitudePanel::GradientMagnitudePanel
    sizer_71_staticbox = new wxStaticBox(this, -1, wxT("Gradient Magnitude"));
    label_56 = new wxStaticText(this, wxID_ANY, wxT("Scale"));
    slideSpatialScale = new wxDoubleSlider(this, SLIDE_SPATIAL_SCALE);
    checkNormalizeScale = new wxCheckBox(this, CHECK_NORMALIZE_SCALE, wxT("Normalize across scale"));

    set_properties();
    do_layout();
    // end wxGlade
    
    this->name = "Gradient";
    
    // setup controls
    this->slideSpatialScale->SetRange(0.1, 24.0, 0.1);
    this->slideSpatialScale->SetValue(1.0);
    
    // setup pipeline
    this->gradient = GradientType::New();
    this->gradient->SetSigma(this->slideSpatialScale->GetValue());
}


BEGIN_EVENT_TABLE(GradientMagnitudePanel, wxPanel)
    EVT_SLIDER(SLIDE_SPATIAL_SCALE, GradientMagnitudePanel::OnSpatialScale)
    // begin wxGlade: GradientMagnitudePanel::event_table
    EVT_CHECKBOX(CHECK_NORMALIZE_SCALE, GradientMagnitudePanel::OnNormalize)
    // end wxGlade
END_EVENT_TABLE();


void GradientMagnitudePanel::OnNormalize(wxCommandEvent &event)
{
    this->gradient->SetNormalizeAcrossScale(this->checkNormalizeScale->IsChecked());
}


void GradientMagnitudePanel::OnSpatialScale(wxCommandEvent &event)
{
    this->gradient->SetSigma(this->slideSpatialScale->GetValue());
}


// wxGlade: add GradientMagnitudePanel event handlers


void GradientMagnitudePanel::set_properties()
{
    // begin wxGlade: GradientMagnitudePanel::set_properties
    slideSpatialScale->SetToolTip(wxT("Gradient scale (standard deviation of Gaussian)"));
    checkNormalizeScale->SetToolTip(wxT("Normalize Gaussians to avoid images fading away "));
    // end wxGlade
}


void GradientMagnitudePanel::do_layout()
{
    // begin wxGlade: GradientMagnitudePanel::do_layout
    wxStaticBoxSizer* sizer_71 = new wxStaticBoxSizer(sizer_71_staticbox, wxVERTICAL);
    wxFlexGridSizer* grid_sizer_24 = new wxFlexGridSizer(2, 2, 5, 5);
    grid_sizer_24->Add(label_56, 0, 0, 0);
    grid_sizer_24->Add(slideSpatialScale, 1, wxEXPAND, 0);
    grid_sizer_24->Add(20, 20, 0, 0, 0);
    grid_sizer_24->Add(checkNormalizeScale, 0, 0, 0);
    grid_sizer_24->AddGrowableCol(1);
    sizer_71->Add(grid_sizer_24, 1, wxEXPAND, 0);
    SetSizer(sizer_71);
    sizer_71->Fit(this);
    // end wxGlade
}

void GradientMagnitudePanel::SetInput(const ImageType* input)
{
    this->gradient->SetInput(input);
}

GradientMagnitudePanel::ImageType* GradientMagnitudePanel::GetOutput()
{
    return this->gradient->GetOutput();
}
