// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Jun 29 18:44:39 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef HORNOPTICALFLOWDIALOG_H
#define HORNOPTICALFLOWDIALOG_H

#include "DataSource.h"
#include "HornOpticalFlowPipeline.h"
#include "ImageTrackerController.h"
#include "wxDoubleSlider.h"
#include "wxIntSlider.h"

// begin wxGlade: ::dependencies
// end wxGlade


class HornOpticalFlowDialog: public wxDialog {
public:
    // begin wxGlade: HornOpticalFlowDialog::ids
    // end wxGlade

    HornOpticalFlowDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    
    enum IDs
    {
        BTN_BROWSE = 3060
    };

private:
    // begin wxGlade: HornOpticalFlowDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: HornOpticalFlowDialog::attributes
    wxStaticBox* sizer_36_staticbox;
    wxStaticBox* sizer_35_staticbox;
    wxStaticText* label_28;
    wxDoubleSlider* sldSmoothing;
    wxStaticText* label_29;
    wxDoubleSlider* sldRegularization;
    wxStaticText* label_30;
    wxIntSlider* sldIterations;
    wxStaticText* label_31;
    wxTextCtrl* textDirectory;
    wxButton* btnBrowse;
    wxStaticText* label_32;
    wxTextCtrl* textPrefix;
    wxCheckBox* checkOpenOutput;
    wxButton* btnRun;
    wxButton* btnHide;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnRun(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnHide(wxCommandEvent &event); // wxGlade: <event_handler>
    
    void SetInput(DataSource::Pointer input);
    void SetController(ImageTrackerController::Pointer controller);
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    
private:
    HornOpticalFlowPipeline::Pointer pipeline;
    DataSource::Pointer input;
    ImageTrackerController::Pointer controller;
    
}; // wxGlade: end class


#endif // HORNOPTICALFLOWDIALOG_H
