// -*- C++ -*- generated by wxGlade 0.6.3 on Sat Aug  2 12:28:09 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef HORNOPTICALFLOWDIALOG_H
#define HORNOPTICALFLOWDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilePatternPanel.h"
#include "wxIntSlider.h"
#include "wxDoubleSlider.h"

// end wxGlade

#include "HornOpticalFlowPipeline.h"
#include "ImageFileSet.h"

class HornOpticalFlowDialog: public wxDialog {
public:
    // begin wxGlade: HornOpticalFlowDialog::ids
    // end wxGlade

    HornOpticalFlowDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    void SetInput(ImageFileSet* input);

private:
    // begin wxGlade: HornOpticalFlowDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    
    ImageFileSet* input;
    HornOpticalFlowPipeline::Pointer pipeline;

protected:
    // begin wxGlade: HornOpticalFlowDialog::attributes
    wxStaticBox* sizer_36_staticbox;
    wxStaticBox* sizer_35_staticbox;
    wxStaticText* label_28;
    wxDoubleSlider* slideDerivativeScale;
    wxStaticText* label_29;
    wxDoubleSlider* slideRegularization;
    wxStaticText* label_30;
    wxIntSlider* slideIterations;
    FilePatternPanel* panelFilePattern;
    wxCheckBox* checkOpenOutput;
    wxButton* buttonRun;
    wxButton* buttonHide;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnRun(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnHide(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // HORNOPTICALFLOWDIALOG_H
