// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Jul 25 08:47:59 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef IMAGEFILESETPANEL_H
#define IMAGEFILESETPANEL_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilterControlPanel.h"
#include "FileSetPanel.h"

// end wxGlade

#include "FileSet.h"
#include "ImageFileSetReader.h"

class ImageFileSetPanel: public FilterControlPanel {
public:
    // begin wxGlade: ImageFileSetPanel::ids
    enum {
        RADIO_PIXEL_TYPE = wxID_HIGHEST + 1102,
        BUTTON_APPLY = wxID_HIGHEST + 1104
    };
    // end wxGlade

    ImageFileSetPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

    typedef FilterControlPanel::ImageType ImageType;
    virtual void SetInput(const ImageType* input);
    virtual ImageType* GetOutput();
    
    ImageFileSetReader::Pointer GetReader();
    
    void SetImageIndex(unsigned int index);
    
    void SetFileSet(const FileSet& files);
    FileSet& GetFileSet();
        
private:
    // begin wxGlade: ImageFileSetPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    ImageFileSetReader::Pointer reader;
    
protected:
    // begin wxGlade: ImageFileSetPanel::attributes
    wxStaticBox* sizer_60_staticbox;
    wxRadioBox* radioPixelType;
    FileSetPanel* panelFileSet;
    wxButton* buttonApply;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnApply(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnPixelType(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // IMAGEFILESETPANEL_H
