// -*- C++ -*- generated by wxGlade 0.4.1 on Mon Oct  1 20:35:55 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef INTEGRATEFLOWDIALOG_H
#define INTEGRATEFLOWDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

#include "DataSource.h"
#include "wxDoubleSlider.h"
#include "IntegrateFlowFieldPipeline.h"

class IntegrateFlowDialog : 
    public wxDialog {
public:
    // begin wxGlade: IntegrateFlowDialog::ids
    // end wxGlade

    enum IDs
    {
        BTN_BROWSE = 3080
    };
    
    IntegrateFlowDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    virtual ~IntegrateFlowDialog();
    
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    void SetInput(DataSource::Pointer input);
    
private:
    // begin wxGlade: IntegrateFlowDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    DataSource::Pointer input;
    IntegrateFlowFieldPipeline::Pointer pipeline;
    
protected:
    // begin wxGlade: IntegrateFlowDialog::attributes
    wxStaticBox* sizer_53_staticbox;
    wxStaticBox* sizer_52_staticbox;
    wxStaticText* label_39;
    wxDoubleSlider* slideStepSize;
    wxStaticText* label_40;
    wxTextCtrl* textDirectory;
    wxButton* btnBrowse;
    wxStaticText* label_41;
    wxTextCtrl* textPrefix;
    wxCheckBox* checkOpenOutput;
    wxButton* btnRun;
    wxButton* btnHide;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // INTEGRATEFLOWDIALOG_H
