// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Aug 14 10:53:36 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef LOGARITHMPANEL_H
#define LOGARITHMPANEL_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilterControlPanel.h"

// end wxGlade

#include "NonZeroLog10ImageFilter.h"

class LogarithmPanel: public FilterControlPanel {
public:
    // begin wxGlade: LogarithmPanel::ids
    // end wxGlade

    LogarithmPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);
    
    typedef FilterControlPanel::ImageType ImageType;
    typedef NonZeroLog10ImageFilter< ImageType, ImageType > LogType;
    
    virtual void SetInput(const ImageType* input);
    virtual ImageType* GetOutput();

private:
    // begin wxGlade: LogarithmPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    
    LogType::Pointer log;

protected:
    // begin wxGlade: LogarithmPanel::attributes
    wxStaticBox* sizer_72_staticbox;
    wxTextCtrl* textMessage;
    // end wxGlade
}; // wxGlade: end class


#endif // LOGARITHMPANEL_H
