// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Aug 14 10:53:36 2008

#include "LogarithmPanel.h"

// begin wxGlade: ::extracode

// end wxGlade


LogarithmPanel::LogarithmPanel(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    FilterControlPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: LogarithmPanel::LogarithmPanel
    sizer_72_staticbox = new wxStaticBox(this, -1, wxT("Logarithm"));
    textMessage = new wxTextCtrl(this, wxID_ANY, wxT("There is nothing to configure for this filter."), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);

    set_properties();
    do_layout();
    // end wxGlade
    
    this->name = "Logarithm";
    
    this->log = LogType::New();
}


void LogarithmPanel::set_properties()
{
    // begin wxGlade: LogarithmPanel::set_properties
    textMessage->Enable(false);
    // end wxGlade
}


void LogarithmPanel::do_layout()
{
    // begin wxGlade: LogarithmPanel::do_layout
    wxStaticBoxSizer* sizer_72 = new wxStaticBoxSizer(sizer_72_staticbox, wxVERTICAL);
    sizer_72->Add(textMessage, 0, wxEXPAND, 0);
    SetSizer(sizer_72);
    sizer_72->Fit(this);
    // end wxGlade
}

void LogarithmPanel::SetInput(const ImageType* input)
{
    this->log->SetInput(input);
}

LogarithmPanel::ImageType* LogarithmPanel::GetOutput()
{
    return this->log->GetOutput();
}
