//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: RegistrationDesign.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_RegistrationDesign_H__
#define __WDR_RegistrationDesign_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "RegistrationDesign_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_CHECK_ABOVE = 10000;
const int ID_TEXT_ABOVE = 10001;
const int ID_SLIDER_ABOVE = 10002;
const int ID_CHECK_BELOW = 10003;
const int ID_TEXT_BELOW = 10004;
const int ID_SLIDER_BELOW = 10005;
const int ID_CHECK_SMOOTH = 10006;
const int ID_TEXT_SMOOTH = 10007;
const int ID_SLIDER_SMOOTH = 10008;
const int ID_CHECK_PREVIEW = 10009;
const int ID_CHECK_TRANSFORM = 10010;
const int ID_TEXT_TRANSFORM = 10011;
const int ID_TRANSFORM_FILE = 10012;
const int ID_CHECK_IMAGES = 10013;
const int ID_TEXT_OUTDIR = 10014;
const int ID_OUT_DIRECTORY = 10015;
const int ID_TEXT = 10016;
const int ID_TEXT_PREFIX = 10017;
const int ID_NEXT = 10018;
const int ID_RUN = 10019;
const int ID_HIDE = 10020;
wxSizer *CreateRegistrationDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int FSD_ADD = 10021;
const int FSD_REMOVE = 10022;
const int ID_LIST_FILES = 10023;
const int ID_TEXT_DIR = 10024;
const int FSD_OK = 10025;
wxSizer *CreateFileSetDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int LOG_MESSAGES = 10026;
const int LOG_COPY = 10027;
const int LOG_CLEAR = 10028;
const int LOG_HIDE = 10029;
wxSizer *CreateLoggerDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IV_CANVAS = 10030;
wxSizer *CreateViewerDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_SCROLLED = 10031;
wxSizer *CreateImageWindowDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_COUNT = 10032;
const int ID_SLIDER_COUNT = 10033;
const int ID_TEXT_SCALE = 10034;
const int ID_SLIDER_SCALE = 10035;
const int ID_TEXT_DISTANCE = 10036;
const int ID_SLIDER_DISTANCE = 10037;
const int ID_TEXT_IMAGE_DIR = 10038;
const int ID_BUTTON_DIRECTORY = 10039;
const int ID_BUTTON_RUN = 10040;
const int ID_BUTTON_HIDE = 10041;
wxSizer *CreateHLTrackerDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_SLIDER = 10042;
const int ID_TEXTCTRL = 10043;
wxSizer *SliderControl( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_PANEL_FILES = 10044;
const int ID_PANEL_IMAGE = 10045;
const int ID_PANEL_CONTROL = 10046;
const int ID_PANEL_LOGGER = 10047;
wxSizer *CreateImageTrackerApp( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_SIGMA = 10048;
const int ID_SLIDER_SIGMA = 10049;
const int ID_TEXT_REGULARIZATION = 10050;
const int ID_SLIDER_REGULARIZATION = 10051;
const int ID_TEXT_RELAXATION = 10052;
const int ID_SLIDER_RELAXATION = 10053;
const int ID_TEXT_ITERATIONS = 10054;
const int ID_SLIDER_ITERATIONS = 10055;
wxSizer *CreateCLGOpticFlowDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int IV_MENU_FILE = 10056;
const int IV_FILES = 10057;
const int ID_MENU = 10058;
const int IV_EXIT = 10059;
const int IV_MENU_ACTIONS = 10060;
const int IV_REGISTER = 10061;
const int IV_TRACK = 10062;
const int IV_CLGOpticFlow = 10063;
const int IV_MENU_VIEW = 10064;
const int IV_MENU_LOGGER = 10065;
const int IV_MENU_HELP = 10066;
const int IV_ABOUT = 10067;
wxMenuBar *CreateViewerMenu();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
