// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Aug 13 12:18:01 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef REGIONPANEL_H
#define REGIONPANEL_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilterControlPanel.h"
#include "wxIntSlider.h"

// end wxGlade

#include "itkRegionOfInterestImageFilter.h"

class RegionPanel: public FilterControlPanel {
public:
    // begin wxGlade: RegionPanel::ids
    enum {
        SLIDE_REGION_LEFT = wxID_HIGHEST + 1148,
        SLIDE_REGION_RIGHT = wxID_HIGHEST + 1149,
        SLIDE_REGION_BOTTOM = wxID_HIGHEST + 1150,
        SLIDE_REGION_TOP = wxID_HIGHEST + 1151
    };
    // end wxGlade

    RegionPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

    typedef FilterControlPanel::ImageType ImageType;
    typedef itk::RegionOfInterestImageFilter< ImageType, ImageType > ROIType;
    typedef ImageType::RegionType RegionType;
    
    virtual void SetInput(const ImageType* input);
    virtual ImageType* GetOutput();
    
private:
    // begin wxGlade: RegionPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    ROIType::Pointer roi;
    
protected:
    // begin wxGlade: RegionPanel::attributes
    wxStaticBox* sizer_12_staticbox;
    wxStaticText* label_18;
    wxStaticText* label_26;
    wxStaticText* label_27;
    wxIntSlider* slideRegionLeft;
    wxIntSlider* slideRegionRight;
    wxStaticText* label_31;
    wxStaticText* label_32;
    wxStaticText* label_40;
    wxIntSlider* slideRegionBottom;
    wxIntSlider* slideRegionTop;
    // end wxGlade
    
    DECLARE_EVENT_TABLE();
    
public:
    virtual void OnRegion(wxCommandEvent &event);
}; // wxGlade: end class


#endif // REGIONPANEL_H
