//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: RegistrationDesign.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_RegistrationDesign_H__
#define __WDR_RegistrationDesign_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "RegistrationDesign_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_CHECK_ABOVE = 10000;
const int ID_TEXT_ABOVE = 10001;
const int ID_SLIDER_ABOVE = 10002;
const int ID_CHECK_BELOW = 10003;
const int ID_TEXT_BELOW = 10004;
const int ID_SLIDER_BELOW = 10005;
const int ID_CHECK_SMOOTH = 10006;
const int ID_TEXT_SMOOTH = 10007;
const int ID_SLIDER_SMOOTH = 10008;
const int ID_CHECK_PREVIEW = 10009;
const int ID_CHECK_TRANSFORM = 10010;
const int ID_TEXT_TRANSFORM = 10011;
const int ID_TRANSFORM_FILE = 10012;
const int ID_CHECK_IMAGES = 10013;
const int ID_TEXT_OUTDIR = 10014;
const int ID_OUT_DIRECTORY = 10015;
const int ID_TEXT = 10016;
const int ID_TEXT_PREFIX = 10017;
const int ID_NEXT = 10018;
const int ID_RUN = 10019;
const int ID_HIDE = 10020;
wxSizer *CreateRegistrationDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_LIST_FILES = 10021;
const int FSD_ADD = 10022;
const int FSD_REMOVE = 10023;
wxSizer *CreateFileSetDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IV_CANVAS = 10024;
wxSizer *CreateViewerDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_COUNT = 10025;
const int ID_SLIDER_COUNT = 10026;
const int ID_TEXT_SCALE = 10027;
const int ID_SLIDER_SCALE = 10028;
const int ID_TEXT_DISTANCE = 10029;
const int ID_SLIDER_DISTANCE = 10030;
const int ID_TEXT_IMAGE_DIR = 10031;
const int ID_BUTTON_DIRECTORY = 10032;
const int ID_BUTTON_RUN = 10033;
const int ID_BUTTON_HIDE = 10034;
wxSizer *CreateHLTrackerDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IT_IMAGE_FILES = 10035;
const int ID_PANEL = 10036;
const int IT_CANVAS = 10037;
const int IT_LOGGER = 10038;
wxSizer *CreateImageTrackerApp( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_SIGMA = 10039;
const int ID_SLIDER_SIGMA = 10040;
const int ID_TEXT_REGULARIZATION = 10041;
const int ID_SLIDER_REGULARIZATION = 10042;
const int ID_TEXT_RELAXATION = 10043;
const int ID_SLIDER_RELAXATION = 10044;
const int ID_TEXT_ITERATIONS = 10045;
const int ID_SLIDER_ITERATIONS = 10046;
wxSizer *CreateCLGOpticFlowDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int MR_CHECK_ABOVE = 10047;
const int MR_SLIDER_ABOVE = 10048;
const int MR_CHECK_BELOW = 10049;
const int MR_SLIDER_BELOW = 10050;
const int MR_SLIDER_LEVELS = 10051;
const int MR_SLIDER_SHRINK = 10052;
const int MR_SLIDER_ITERATIONS = 10053;
const int MR_SLIDER_MAXSTEP = 10054;
const int MR_SLIDER_MINSTEP = 10055;
const int MR_SLIDER_SCALE = 10056;
const int MR_TEXT_TRANSFORM = 10057;
const int MR_TRANSFORM_FILE = 10058;
const int MR_TEXT_OUTDIR = 10059;
const int MR_OUT_DIRECTORY = 10060;
const int MR_TEXT_PREFIX = 10061;
const int MR_BUTTON_RUN = 10062;
const int MR_BUTTON_HIDE = 10063;
wxSizer *CreateMultiResolutionRegistrationDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int IV_MENU_FILE = 10064;
const int IV_FILES = 10065;
const int ID_MENU = 10066;
const int IV_EXIT = 10067;
const int IV_MENU_ACTIONS = 10068;
const int IV_REGISTER = 10069;
const int IV_MULTI_RES = 10070;
const int IV_TRACK = 10071;
const int IV_CLGOpticFlow = 10072;
const int IV_MENU_HELP = 10073;
const int IV_ABOUT = 10074;
const int IV_LOGGING = 10075;
const int IV_LOG_ERROR = 10076;
const int IV_LOG_WARN = 10077;
const int IV_LOG_INFO = 10078;
const int IV_LOG_DEBUG = 10079;
const int IV_LOG_VERBOSE = 10080;
wxMenuBar *CreateViewerMenu();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
