// -*- C++ -*- generated by wxGlade 0.4.1 on Tue Jan 30 21:01:15 2007

#include <wx/wx.h>
#include <wx/image.h>
        
#include "DataSource.h"
#include "FilePatternPanel.h"
#include "RemovePartialOcclusionsPipeline.h"
#include "wxDoubleSlider.h"
        
#ifndef REMOVEOCCLUSIONSDIALOG_H
#define REMOVEOCCLUSIONSDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade


class RemoveOcclusionsDialog: public wxDialog {
public:
    // begin wxGlade: RemoveOcclusionsDialog::ids
    // end wxGlade

    RemoveOcclusionsDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    
private:
    // begin wxGlade: RemoveOcclusionsDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: RemoveOcclusionsDialog::attributes
    wxStaticBox* sizer_58_staticbox;
    wxStaticBox* sizer_18_staticbox;
    wxStaticText* label_1;
    wxComboBox* comboMetric;
    wxStaticText* label_3;
    wxSlider* slidePercentile;
    wxStaticText* label_4;
    wxDoubleSlider* slidePadding;
    FilePatternPanel* panelFilePattern;
    wxStaticText* label_5;
    wxTextCtrl* textTransmission;
    wxCheckBox* checkOpenOutput;
    wxButton* btnRun;
    wxButton* btnHide;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnRun(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnHide(wxCommandEvent &event); // wxGlade: <event_handler>
    
public:
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    
    DataSource::Pointer GetInput() const
    { return this->input; }
    
    void SetInput(DataSource::Pointer input)
    { this->input = input; }
    
private:
    RemovePartialOcclusionsPipeline::Pointer pipeline;
    DataSource::Pointer input;
}; // wxGlade: end class


#endif // REMOVEOCCLUSIONSDIALOG_H
