// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jul 29 16:37:25 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef REMOVEOCCLUSIONSDIALOG_H
#define REMOVEOCCLUSIONSDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilePatternPanel.h"
#include "wxDoubleSlider.h"

// end wxGlade

#include "ImageFileSet.h"
#include "RemovePartialOcclusionsPipeline.h"

class RemoveOcclusionsDialog: public wxDialog {
public:
    // begin wxGlade: RemoveOcclusionsDialog::ids
    // end wxGlade

    RemoveOcclusionsDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();
    
    void SetInput(ImageFileSet* input);

private:
    // begin wxGlade: RemoveOcclusionsDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    
    RemovePartialOcclusionsPipeline::Pointer pipeline;
    ImageFileSet* input;

protected:
    // begin wxGlade: RemoveOcclusionsDialog::attributes
    wxStaticBox* sizer_58_staticbox;
    wxStaticBox* sizer_18_staticbox;
    wxStaticText* label_1;
    wxComboBox* comboMetric;
    wxStaticText* label_3;
    wxSlider* slidePercentile;
    wxStaticText* label_4;
    wxDoubleSlider* slidePadding;
    FilePatternPanel* panelFilePattern;
    wxStaticText* label_5;
    wxTextCtrl* textTransmission;
    wxCheckBox* checkOpenOutput;
    wxButton* buttonRun;
    wxButton* buttonHide;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnRun(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnHide(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // REMOVEOCCLUSIONSDIALOG_H
