// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Aug 14 13:51:04 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef SAVEFILTERIMAGEDIALOG_H
#define SAVEFILTERIMAGEDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilePatternPanel.h"

// end wxGlade


class SaveFilterImageDialog: public wxDialog {
public:
    // begin wxGlade: SaveFilterImageDialog::ids
    // end wxGlade

    SaveFilterImageDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    
    virtual bool TransferDataToWindow();
    virtual bool TransferDataFromWindow();

private:
    // begin wxGlade: SaveFilterImageDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: SaveFilterImageDialog::attributes
    wxStaticBox* sizer_74_staticbox;
    FilePatternPanel* panelFilePattern;
    wxRadioBox* radioPixelType;
    wxCheckBox* checkRescale;
    wxButton* buttonRun;
    wxButton* buttonCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnOK(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // SAVEFILTERIMAGEDIALOG_H
