// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Aug  4 15:49:54 2008

#include "ScalarImageControlDialog.h"

// begin wxGlade: ::extracode

// end wxGlade


ScalarImageControlDialog::ScalarImageControlDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME)
{
    // begin wxGlade: ScalarImageControlDialog::ScalarImageControlDialog
    panelScalarImageControl = new ScalarImageControlPanel(this, wxID_ANY);

    set_properties();
    do_layout();
    // end wxGlade
}


void ScalarImageControlDialog::set_properties()
{
    // begin wxGlade: ScalarImageControlDialog::set_properties
    SetTitle(wxT("Window/Contrast"));
    // end wxGlade
}


void ScalarImageControlDialog::do_layout()
{
    // begin wxGlade: ScalarImageControlDialog::do_layout
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    sizer_7->Add(panelScalarImageControl, 1, wxEXPAND, 0);
    SetSizer(sizer_7);
    sizer_7->Fit(this);
    Layout();
    // end wxGlade
}

bool ScalarImageControlDialog::TransferDataToWindow()
{
    return this->panelScalarImageControl->TransferDataToWindow();
}
