// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Aug  4 15:51:32 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef SCALARIMAGECONTROLPANEL_H
#define SCALARIMAGECONTROLPANEL_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "wxDoubleSlider.h"

// end wxGlade

#include "ScalarImageVisualization.h"

class ScalarImageControlPanel: public wxPanel {
public:
    // begin wxGlade: ScalarImageControlPanel::ids
    enum {
        CHECK_VISIBILITY = wxID_HIGHEST + 1095,
        SLIDE_WINDOW_MAX = wxID_HIGHEST + 1097,
        SLIDE_WINDOW_MIN = wxID_HIGHEST + 1098,
        COMBO_WINDOW_RANGE = wxID_HIGHEST + 1099,
        BUTTON_AUTO = wxID_HIGHEST + 1101
    };
    // end wxGlade

    ScalarImageControlPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);
    
    void SetPipeline(ScalarImageVisualization::Pointer pipeline);
    virtual bool TransferDataToWindow();
    
private:
    // begin wxGlade: ScalarImageControlPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ScalarImageControlPanel::attributes
    wxStaticBox* sizer_14_staticbox;
    wxStaticBox* sizer_42_staticbox;
    wxCheckBox* checkVisibility;
    wxStaticText* label_36;
    wxDoubleSlider* slideWindowMax;
    wxStaticText* label_37;
    wxDoubleSlider* slideWindowMin;
    wxStaticText* label_38;
    wxComboBox* comboWindowRange;
    wxButton* buttonAuto;
    // end wxGlade

    DECLARE_EVENT_TABLE();
    
    ScalarImageVisualization::Pointer GetPipeline();

public:
    virtual void OnWindow(wxCommandEvent &event);
    virtual void OnVisibility(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRange(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnAuto(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // SCALARIMAGECONTROLPANEL_H
