// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Aug  4 15:51:32 2008

#include "ScalarImageControlPanel.h"

// begin wxGlade: ::extracode

// end wxGlade

#include "itkStatisticsImageFilter.h"

#include "ImageTrackerController.h"
#include "wxUtils.h"

ScalarImageControlPanel::ScalarImageControlPanel(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: ScalarImageControlPanel::ScalarImageControlPanel
    sizer_14_staticbox = new wxStaticBox(this, -1, wxT("Scalar Image"));
    sizer_42_staticbox = new wxStaticBox(this, -1, wxT("Contrast"));
    checkVisibility = new wxCheckBox(this, CHECK_VISIBILITY, wxT("Visible"));
    label_36 = new wxStaticText(this, wxID_ANY, wxT("Maximum"));
    slideWindowMax = new wxDoubleSlider(this, SLIDE_WINDOW_MAX);
    label_37 = new wxStaticText(this, wxID_ANY, wxT("Minimum"));
    slideWindowMin = new wxDoubleSlider(this, SLIDE_WINDOW_MIN);
    label_38 = new wxStaticText(this, wxID_ANY, wxT("Range"));
    const wxString comboWindowRange_choices[] = {
        wxT("8-bit"),
        wxT("16-bit"),
        wxT("From Image")
    };
    comboWindowRange = new wxComboBox(this, COMBO_WINDOW_RANGE, wxT(""), wxDefaultPosition, wxDefaultSize, 3, comboWindowRange_choices, wxCB_DROPDOWN|wxCB_READONLY);
    buttonAuto = new wxButton(this, BUTTON_AUTO, wxT("&Auto"));

    set_properties();
    do_layout();
    // end wxGlade
    
    // Setup sliders initially (8-bit)
    this->slideWindowMax->SetRange(0.0, 255.0, 1.0);
    this->slideWindowMin->SetRange(0.0, 255.0, 1.0);
    this->slideWindowMax->SetValue(255.0);
    this->slideWindowMin->SetValue(0.0);
}


BEGIN_EVENT_TABLE(ScalarImageControlPanel, wxPanel)
    EVT_SLIDER(SLIDE_WINDOW_MAX, ScalarImageControlPanel::OnWindow)
    EVT_SLIDER(SLIDE_WINDOW_MIN, ScalarImageControlPanel::OnWindow)
    // begin wxGlade: ScalarImageControlPanel::event_table
    EVT_CHECKBOX(CHECK_VISIBILITY, ScalarImageControlPanel::OnVisibility)
    EVT_COMBOBOX(COMBO_WINDOW_RANGE, ScalarImageControlPanel::OnRange)
    EVT_BUTTON(BUTTON_AUTO, ScalarImageControlPanel::OnAuto)
    // end wxGlade
END_EVENT_TABLE();


void ScalarImageControlPanel::OnVisibility(wxCommandEvent &event)
{
    ScalarImageVisualization::Pointer pipeline = this->GetPipeline();
    if (pipeline && pipeline.IsNotNull())
        pipeline->SetVisibility(this->checkVisibility->IsChecked());
}


void ScalarImageControlPanel::OnRange(wxCommandEvent &event)
{
    ScalarImageVisualization::Pointer pipeline = this->GetPipeline();
    if (pipeline && pipeline.IsNotNull())
    {
        typedef unsigned char EightBit;
        typedef unsigned short SixteenBit;
        
        std::string val(nano::wx2std(this->comboWindowRange->GetValue()));
        if (val == "8-bit")
        {
            this->slideWindowMax->SetRange(std::numeric_limits<EightBit>::min(), 
                                           std::numeric_limits<EightBit>::max());
            this->slideWindowMin->SetRange(std::numeric_limits<EightBit>::min(), 
                                           std::numeric_limits<EightBit>::max());
        }
        else if (val == "16-bit")
        {
            this->slideWindowMax->SetRange(std::numeric_limits<SixteenBit>::min(), 
                                           std::numeric_limits<SixteenBit>::max());
            this->slideWindowMin->SetRange(std::numeric_limits<SixteenBit>::min(), 
                                           std::numeric_limits<SixteenBit>::max());
        }
        else // Use image min/max
        {
            typedef itk::StatisticsImageFilter< ScalarImageVisualization::InputImageType > StatsType;
            StatsType::Pointer stats = StatsType::New();
            stats->SetInput(pipeline->GetInput());
            stats->Update();
            this->slideWindowMax->SetRange(stats->GetMinimum(), stats->GetMaximum());
            this->slideWindowMin->SetRange(stats->GetMinimum(), stats->GetMaximum());           
        }
    }
}


void ScalarImageControlPanel::OnAuto(wxCommandEvent &event)
{
    ScalarImageVisualization::Pointer pipeline = this->GetPipeline();
    if (pipeline && pipeline.IsNotNull())
    {
        typedef itk::StatisticsImageFilter< ScalarImageVisualization::InputImageType > StatsType;
        StatsType::Pointer stats = StatsType::New();
        stats->SetInput(pipeline->GetInput());
        stats->Update();
        this->slideWindowMax->SetRange(stats->GetMinimum(), stats->GetMaximum());
        this->slideWindowMax->SetValue(stats->GetMaximum());
        this->slideWindowMin->SetRange(stats->GetMinimum(), stats->GetMaximum());
        this->slideWindowMin->SetValue(stats->GetMinimum());
        this->OnWindow(event);
    }
}

// wxGlade: add ScalarImageControlPanel event handlers


void ScalarImageControlPanel::OnWindow(wxCommandEvent &event)
{
    ScalarImageVisualization::Pointer pipeline = this->GetPipeline();
    if (pipeline && pipeline.IsNotNull())
    {
        pipeline->SetWindowMaximum(this->slideWindowMax->GetValue());
        pipeline->SetWindowMinimum(this->slideWindowMin->GetValue());
    }
}

void ScalarImageControlPanel::set_properties()
{
    // begin wxGlade: ScalarImageControlPanel::set_properties
    checkVisibility->SetToolTip(wxT("Show or hide the image data"));
    checkVisibility->SetValue(1);
    slideWindowMax->SetToolTip(wxT("Adjust the maximum displayed image value (mapped to white)"));
    slideWindowMin->SetToolTip(wxT("Adjust the minimum displayed image value (mapped to black)"));
    comboWindowRange->SetToolTip(wxT("Select the range of values visible on the sliders above"));
    comboWindowRange->SetSelection(2);
    buttonAuto->SetToolTip(wxT("Maximize the contrast for the currently displayed image"));
    // end wxGlade
}


void ScalarImageControlPanel::do_layout()
{
    // begin wxGlade: ScalarImageControlPanel::do_layout
    wxStaticBoxSizer* sizer_14 = new wxStaticBoxSizer(sizer_14_staticbox, wxVERTICAL);
    wxStaticBoxSizer* sizer_42 = new wxStaticBoxSizer(sizer_42_staticbox, wxVERTICAL);
    wxFlexGridSizer* grid_sizer_14 = new wxFlexGridSizer(4, 2, 5, 5);
    sizer_14->Add(checkVisibility, 0, 0, 0);
    grid_sizer_14->Add(label_36, 0, 0, 0);
    grid_sizer_14->Add(slideWindowMax, 1, wxEXPAND, 0);
    grid_sizer_14->Add(label_37, 0, 0, 0);
    grid_sizer_14->Add(slideWindowMin, 1, wxEXPAND, 0);
    grid_sizer_14->Add(label_38, 0, 0, 0);
    grid_sizer_14->Add(comboWindowRange, 0, wxEXPAND, 0);
    grid_sizer_14->Add(20, 20, 0, 0, 0);
    grid_sizer_14->Add(buttonAuto, 0, 0, 0);
    grid_sizer_14->AddGrowableCol(1);
    sizer_42->Add(grid_sizer_14, 1, wxEXPAND, 0);
    sizer_14->Add(sizer_42, 1, wxEXPAND, 0);
    SetSizer(sizer_14);
    sizer_14->Fit(this);
    // end wxGlade
}

bool ScalarImageControlPanel::TransferDataToWindow()
{
    ScalarImageVisualization::Pointer pipeline = this->GetPipeline();
    if (pipeline && pipeline.IsNotNull())
    {
        this->checkVisibility->SetValue(pipeline->GetVisibility());
        this->slideWindowMax->SetRange(pipeline->GetWindowMinimum(), pipeline->GetWindowMaximum());
        this->slideWindowMin->SetRange(pipeline->GetWindowMinimum(), pipeline->GetWindowMaximum());
        this->slideWindowMax->SetValue(pipeline->GetWindowMaximum());
        this->slideWindowMin->SetValue(pipeline->GetWindowMinimum());
    }

    return true;
}

ScalarImageVisualization::Pointer ScalarImageControlPanel::GetPipeline()
{
    if (ImageTrackerController::Instance()->GetImageCount() > 0)
        return dynamic_cast<ScalarImageVisualization*>(ImageTrackerController::Instance()->GetImageVisualization().GetPointer());
    else
        return NULL;
}

void ScalarImageControlPanel::SetPipeline(ScalarImageVisualization::Pointer pipeline)
{
    // ignored
}
