// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Jul 25 08:47:59 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef THRESHOLDPANEL_H
#define THRESHOLDPANEL_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "FilterControlPanel.h"
#include "wxDoubleSlider.h"

// end wxGlade

#include "itkThresholdImageFilter.h"

class ThresholdPanel: public FilterControlPanel {
public:
    // begin wxGlade: ThresholdPanel::ids
    enum {
        SLIDE_UPPER_BOUND = wxID_HIGHEST + 1106,
        SLIDE_LOWER_BOUND = wxID_HIGHEST + 1107,
        COMBO_RANGE = wxID_HIGHEST + 1108
    };
    // end wxGlade

    ThresholdPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

    typedef FilterControlPanel::ImageType ImageType;
    typedef itk::ThresholdImageFilter< ImageType > ThresholdType;
    
    virtual void SetInput(const ImageType* input);
    virtual ImageType* GetOutput();
    
private:
    // begin wxGlade: ThresholdPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    ThresholdType::Pointer threshold;
    
protected:
    // begin wxGlade: ThresholdPanel::attributes
    wxStaticBox* sizer_59_staticbox;
    wxStaticText* label_12;
    wxDoubleSlider* slideUpperBound;
    wxStaticText* label_13;
    wxDoubleSlider* slideLowerBound;
    wxStaticText* label_14;
    wxComboBox* comboRange;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnBounds(wxCommandEvent &event);
    virtual void OnRange(wxCommandEvent &event); // wxGlade: <event_handler>    
}; // wxGlade: end class


#endif // THRESHOLDPANEL_H
