// -*- C++ -*- generated by wxGlade 0.4.1 on Mon Oct  8 14:50:01 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef VECTORHEIGHTMAPCONTROLPANEL_H
#define VECTORHEIGHTMAPCONTROLPANEL_H

#include "wxDoubleSlider.h"
#include "VectorHeightMapVisualization.h"

// begin wxGlade: ::dependencies
// end wxGlade


class VectorHeightMapControlPanel: public wxPanel {
public:
    enum ids
    {
        CBX_VISIBLE,
        CMB_COLOR_MAP_TYPE,
        SLD_COLOR_MAP_MAXIMUM,
        SLD_COLOR_MAP_MINIMUM,
        SLD_SCALE_FACTOR,
        CMB_MAGNITUDE_FUNCTION
    };
    
    // begin wxGlade: VectorHeightMapControlPanel::ids
    // end wxGlade

    VectorHeightMapControlPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

    /**
     * Get/Set the visualization pipeline
     */
    VectorHeightMapVisualization::Pointer GetPipeline();
    void SetPipeline(VectorHeightMapVisualization::Pointer pipeline);
    
    virtual bool TransferDataToWindow();
    
private:
    // begin wxGlade: VectorHeightMapControlPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    VectorHeightMapVisualization::Pointer pipeline;
    
protected:
    // begin wxGlade: VectorHeightMapControlPanel::attributes
    wxStaticBox* sizer_56_staticbox;
    wxCheckBox* checkVisible;
    wxStaticText* label_46;
    wxComboBox* comboColorMapType;
    wxStaticText* label_47;
    wxDoubleSlider* slideColorMapMaximum;
    wxStaticText* label_48;
    wxDoubleSlider* slideColorMapMinimum;
    wxStaticText* label_52;
    wxDoubleSlider* slideScaleFactor;
    wxStaticText* label_53;
    wxComboBox* comboMagnitudeFunction;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnScaleFactor(wxCommandEvent &event);
    void OnVisible(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnColorMapType(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnMagnitudeFunction(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // VECTORHEIGHTMAPCONTROLPANEL_H
