// -*- C++ -*- generated by wxGlade 0.4.1 on Mon Oct  1 16:19:36 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WXDOUBLESLIDER_H
#define WXDOUBLESLIDER_H

// begin wxGlade: ::dependencies
// end wxGlade


class wxDoubleSlider: public wxPanel {
public:
    // begin wxGlade: wxDoubleSlider::ids
    // end wxGlade

    wxDoubleSlider(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxTAB_TRAVERSAL | wxNO_BORDER);

    virtual ~wxDoubleSlider();
    
    void SetRange(double min, double max, double interval = 0.1);
    void SetValue(double value);
    double GetValue();
    int GetValueAsInt();
    
    double GetMin();
    double GetMax();
    
    void SetFormat(const std::string& format);
    
    void SetEnforceRange(bool enforce);
    bool GetEnforceRange();
    
private:
    // begin wxGlade: wxDoubleSlider::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    double minimum;
    double maximum;
    double interval;
    double value;
    wxString format;
    bool enforceRange;
    
    bool CheckRange(double val);
    void GenerateEvent();
    
    int DoubleToSlider();
    double SliderToDouble();
    
protected:
    // begin wxGlade: wxDoubleSlider::attributes
    wxSlider* sldSlider;
    wxTextCtrl* textValue;
    wxStaticText* labelMinimum;
    wxStaticText* labelMaximum;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnSlider(wxScrollEvent &event); // wxGlade: <event_handler>
    void OnText(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // WXDOUBLESLIDER_H
