// -*- C++ -*- generated by wxGlade 0.4.1 on Mon Oct  1 12:40:16 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WXINTSLIDER_H
#define WXINTSLIDER_H

// begin wxGlade: ::dependencies
// end wxGlade


class wxIntSlider: public wxPanel {
public:
    // begin wxGlade: wxIntSlider::ids
    // end wxGlade

    wxIntSlider(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxTAB_TRAVERSAL | wxNO_BORDER);

    virtual ~wxIntSlider();
    
    void SetRange(int min, int max);
    void SetValue(int value);
    int GetValue();
    
    int GetMin();
    int GetMax();
    
    void SetFormat(const std::string& format);
    
    void SetEnforceRange(bool enforce);
    bool GetEnforceRange();
    
private:
    // begin wxGlade: wxIntSlider::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    int minimum;
    int maximum;
    int value;
    wxString format;
    bool enforceRange;
    
    bool CheckRange(int val);
    void GenerateEvent();
    
protected:
    // begin wxGlade: wxIntSlider::attributes
    wxSlider* sldSlider;
    wxTextCtrl* textValue;
    wxStaticText* labelMinimum;
    wxStaticText* labelMaximum;
    // end wxGlade

    DECLARE_EVENT_TABLE();
    
public:
    void OnSlider(wxScrollEvent &event); // wxGlade: <event_handler>
    void OnText(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // WXINTSLIDER_H
